### ISSUE TITLE
Unhandled error causing panic

### ISSUE THREAD

**Issue by razum90** [recws-org/recws#42]
Hi,

I encountered the following error in my application: 

`panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d96d0]goroutine 59856 [running]:github.com/gorilla/websocket.(*Conn).SetPongHandler(0x0, 0xc003712960) /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1160 +0x20github.com/recws-org/recws.(*RecConn).keepAlive(0x1399a00) /go/pkg/mod/github.com/recws-org/recws@v1.3.1/recws.go:365 +0xc5github.com/recws-org/recws.(*RecConn).connect(0x1399a00) /go/pkg/mod/github.com/recws-org/recws@v1.3.1/recws.go:422 +0x3cacreated by github.com/recws-org/recws.(*RecConn).CloseAndReconnect /go/pkg/mod/github.com/recws-org/recws@v1.3.1/recws.go:64 +0x4d`

Looks to happen because the error on this line is not being handled, but I might be wrong: https://github.com/recws-org/recws/blob/37f9e465dfb0a29879f4be02e694165e77cb6b8c/recws.go#L365

Any ideas how to go about this?

Thank you.

**Comment by nikepan** [comment]
It can happens when ConnectHandler execute too long

**Comment by loeffel-io** [comment]
Please see #61
